config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts, :only => [:index, :create, :new, :update, :edit, :destory] 

  resources :pages, :only => [] do
    get 'resume'
  end

  resources :messages

  root :to => 'pages#resume' 
end

app/models/message.rb
class Message < ActiveRecord::Base
  validates_presence_of :title, :content
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates_presence_of :title, :content
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name, :email
  validates_uniqueness_of :email, :case_sensitive => false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :pass_pathname_to_gon

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end

  private

  def user_not_authorized
    flash[:error] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  def pass_pathname_to_gon
    # Pass controller_name to AngularJS
    # Just for demo pathname can actually be accessed from $window module 
    gon.location = self.controller_name 
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params[:message]
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def resume

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :new, :create]

  def index
    @posts = policy_scope(Post)
  end

  def show
    authorize @post
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    authorize @post

    if @post.save
      redirect_to posts_path, success: 'Post was successfully updated'
    else
      render :new
    end
  end

  def update
    authorize @post

    if @post.update(post_params)
      redirect_to @posts, success: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    authorize @post

    if @post.destroy
      redirect_to posts_url, success: 'Post was successfully destroyed.'
    else
      redirect_to root_path, error: 'We are sorry but something went wrong.'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params[:post].permit([:title, :content])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flash_messages_helper.rb
module FlashMessagesHelper

  def flash_messages
    content_tag(:section, :class => 'flash-messages') do
      content_tag(:ul) do
        flash.map do |key, value|
          concat content_tag(:li, value, :class => "flash-message flash-#{key}")
        end
      end
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<%= favicon_link_tag 'dna.png' %>

<head>
  <title>Jiangnan</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= include_gon %>
  <%= csrf_meta_tags %>
</head>

<body class="abstract">

  <div class='js-side-menu'>
    <div class='navbar navbar-default navbar-fixed-top'>
      <div class='top-nav-menu-button'>
        Menu
        <i class="fa fa-bars"></i>
      </div>
    </div>

    <div class='side-nav'>
      <ul class='side-menu'>

        <li> <%= link_to "Resume",  root_path %> </li>
        <li> <%= link_to "Blog",    posts_path %> </li>

        <li> <a href="mailto:xuwupeng2000@gmail.com" target="_top">Email Me</a> </li>
        <li>
          <a href="http://www.linkedin.com/pub/peng-wu/49/5b5/7ab" target="_blank"> Linkedin Profile </a>
          <i class="fa fa-linkedin-square"></i>
        </li>

        <% unless current_user  %>
          <li> <%= link_to "Login ",  new_user_session_path %> </li>
          <li> <%= link_to "Sign Up", new_user_registration_path %> </li>
        <% end %>

        <% if current_user %>
          <li> <%= link_to "Log off ", destroy_user_session_path, method: :delete %> </li>
        <% end %>

      </ul>
    </div>
  </div>

  <%= flash_messages %>

  <%= yield %>

</body>

<!-- FOOTER -->
<footer> </footer>
<!-- FOOTER -->

</html>

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<h1>Listing messages</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/index.html.haml
%h1 Listing messages
  %table
    %thead
      %tr
        %th{ :colspan="3" }
    %tbody
      = @messages.each do |m|
        %tr
          %td= link_to 'Show', message 
          %td= link_to 'Edit', edit_message_path(message)
          %td= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' }
      = end

%br
= link_to 'New Message', new_message_path

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/pages/_features.html.erb
<!-- START THE FEATURETTES -->
<section class="container-wrapper features">
  <div class="container ruby-icon">

    <div class="row featurette">
      <h2> Ruby on Rails<span class="text-muted"> Full stack development </span></h2>

      <div class="col-md-6 col-lg-6 col-sm-12">
        <h5>Front-end Development</h5>
        <ul class="skills">
          <li>Experienced in CSS, SCSS. </li>
          <li>Experienced in implementing and applying Pattern Library. </li>
          <li>Experienced in pure JavaScript, jQuery. </li>
          <li>Experienced in Front-end MVC frameworks - <strong>AngularJS</strong>, <strong>BackboneJS</strong>.</li>
          <li>Experienced in CoffeeScript. </li>
          <li>Able to Create <strong> Real Responsive Design </strong>. </li>
        </ul>
      </div>

      <div class="col-md-6 col-lg-6 col-sm-12">
        <h5>Back-end Development</h5>
        <ul class="skills">
          <li>Experienced in tweaking complex Database Query (<strong>PostgreSQL</strong>, Oracle). </li>
          <li>Experienced in bootstrping scale <strong>JSON API</strong>. </li>
          <li>Experienced in optimizing caching efficiency. </li>
          <li>Experienced in implementing highly costomized Capistrano 3 deploy scripts. <strong><a href="https://github.com/xuwupeng2000/capsitrano-scm-gitcopy">My Work: capsitrano-scm-gitcopy</a></strong> </li>
          <li>Experienced in event-driven Rake application. </li>
          <li>Experienced in <strong>Real World Software Engineering</strong>. </li>
          <li>Depth knowledge of Networking security And Application security. </li>
          <li>Depth knowledge of Software Engineering, Agile methods, MVC, OOA, TDD. </li>
        </ul>
      </div>

    </div>

    <div class="row featurette">
      <div class="col-md-6 col-lg-6 col-sm-12">
        <h5>Upgrading RoR</h5>
        <ul class="skills">
          <li>One of the few professionals know how to <strong>Upgrade complex RoR system.</strong> </li>
          <li>Managed to upgrade couple enterprise applications from Ruby 1.8 to Ruby 1.9, from Rails 3.0 to Rails 3.2. </li>
          <li>Have so many experiences with <strong>RSpec and Cucumber</strong>. </li>
          <li>Able to create sophisticated specs to target the most complex scenarios. </li>
        </ul>
      </div>

      <div class="col-md-6 col-lg-6 col-sm-12col-md-6">
        <h5>Warden Warrior</h5>
        <ul class="skills">
          <li>Been designing and implementing enterprise-level authentication & authentication system. </li>
          <li>Know everything about Warden Gem and customized authentication strategies. </li>
        </ul>
      </div>
    </div>

  </div>
</section>

<hr class="featurette-divider">

<section class="container-wrapper bg-darker">
  <div class="container coffee-icon">
    <div class="row featurette">

      <div class="col-md-8 col-lg-8 col-sm-12">
        <h2 class="featurette-heading"> Android Development <span class="text-muted"> Real word application </span></h2>
        <ul class="skills">
          <li> Experienced in Java, from Jave Core, Java EE to Android </li>
          <li> Able to implement complex algorithms from scratch eg: <strong>DB4, Haar Wavelet Transform</strong>, FFT Transform, SVM Classifier and KNN Classifier </li>
        </ul>
      </div>

      <div class="col-md-4 col-lg-4 col-sm-12">  <%= image_tag "java.png", id: "java" %> </div>

    </div>
  </div>
</section>


<hr class="featurette-divider">

<section class="container-wrapper">
  <div class="container coffee-icon">
    <div class="row featurette">

      <div class="col-md-4 col-lg-4 col-sm-12"> <%= image_tag "cl.png", id: "cl" %> </div>

      <div class="col-md-8 col-lg-8 col-sm-12">
        <h2 class="featurette-heading"> OpenCl <span class="text-muted"> Advanced understanding of Computer Science </span></h2>
        <ul class="skills">
          <li> Experienced in C, OpenCL </li>
          <li> Depth knowledge of Parallel Computing, Concurrent Programming and <strong>GPUGPU Programming</strong> </li>
          <li> Depth knowledge of Exact String Matching </li>
          <li> Experienced in <strong>Shell scripting</strong>. </li>
        </ul>
      </div>

    </div>
  </div>
</section>

<hr class="featurette-divider">
<!-- /END THE FEATURETTES -->

app/views/pages/resume.html.erb
<section class="container">
  <div class="row">
    <div class="col-lg-8">
      <div id="about-me">
        <h2>About Me</h2>
        <p class="lead">My name is Jack Wu. I come from Beijing, China.</p>
        <p class="lead">
          I have been in New Zealand for 5 years.  
          I did my Master's Degree (Information Science) at Otago Uni. 
          Currently I am working for Figured as a Senior Software Developer. 
        </p>
      </div>
    </div>
    <div class="col-lg-4">
      <div id="me"></div>
    </div>
  </div>
</section>

<hr class="featurette-divider">

<section class="container">

  <div class="row">

    <h2>Eduction</h2>

    <div class="col-lg-4 col-md-4 col-sm-12">
      <div class="img-cut"> <%= image_tag "otago.png", :id => "otato" %> </div>
      <h6>2010 - 2012</h6>
      <p> Master of Information Science Otago Uni </p>
    </div>

    <div class="col-lg-4 col-md-4 col-sm-12">
      <div class="img-cut"> <%= image_tag "scau.png", :id => "scau" %> </div>
      <h6>2004 - 2008</h6>
      <p> Bachelor Degree of Computer Science SCAU Uni </p>
    </div>

  </div>

  <div class="row">

    <h2>Working Experiences</h2>

    <div class="col-lg-4 col-md-4 col-sm-12">
      <div class="img-cut"> <%= image_tag "hsbc.png", :id => "hsbc" %> </div>
      <h6>2009 - 2010</h6>
      <p> Java Developer </p>
    </div>

    <div class="col-lg-4 col-md-4 col-sm-12">
      <div class="img-cut"> <%= image_tag "nzx.png", :id => "nzx" %> </div>
      <h6>2013 - 2014</h6>
      <p> NZX, Ruby on Rails Analyist </p>
    </div>

    <div class="col-lg-4 col-md-4 col-sm-12">
      <div class="img-cut"> <%= image_tag "figured.png", :id => "figured" %> </div>
      <h6>2014 - Current</h6>
      <p> Figured, Senior Developer </p>
    </div>

  </div>


</section><!-- /.container -->

<hr class="featurette-divider">

<%= render partial: 'features' %>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<section class="container">
  <div class="col-lg-8 col-sm-12 slide">
    <h1>Editing post</h1>

    <%= render 'form' %>
  </div>
</section>

app/views/posts/index.html.erb
<section class="container">
  <div class="col-lg-12 col-sm-12">
    <h2>Jack Wu's Demo Blog</h2>
    <div class="nag">
      <small>* This is really just for demo Authentication and Authorization. It does not have much features to offer yet.</small>
    </div>

    <div class="post-new">
      <i class="fa fa-plus-circle"></i>
      <%= link_to "New Post", new_post_path %>
    </div>
    <div class="all-posts">
      <% @posts.each do |post| %>

      <div class="post-entry">

        <div clss="row post-bar">
          <div class="col-lg-12 col-sm-12">
            <h4 class="post-title"><%= post.title %></h4>

          </div>
        </div>

        <div class="post-content row">
          <div class="col-lg-12 col-sm-12"> <%= post.content %> </div>
        </div>

        <div class="post-actions row pull-right">
          <div class="col-lg-12 col-sm-12">
            <% if current_user && policy(:post).edit? %>
              <span>
                <i class="fa fa-pencil-square-o"></i>
                <%= link_to 'Edit', edit_post_path(post) %>
              </span>

              <span>
                <i class="fa fa-trash-o"></i>
                <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %>
              </span>
            <% end %>
          </div>
        </div>
      </div>

      <hr/>

      <% end %>
    </div>

  </div>
</section>

app/views/posts/new.html.erb
<section class="container">
  <div class="col-lg-8 col-sm-12 slide">
    <h1>New post</h1>

    <%= render 'form' %>
  </div>
</section>

app/views/users/shared/_links.erb
<div class="dna-icon">
  <ul class="devise-bar">
    <%- if devise_mapping.omniauthable? %>
      <%- resource_class.omniauth_providers.each do |provider| %>
        <li><%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %></li>
      <% end -%>
    <% end -%>
  </ul>

  <ul class="devise-bar">
    <%- if controller_name != 'sessions' %>
      <li><%= link_to "Log in", new_session_path(resource_name) %></li>
    <% end -%>
  </ul>

  <ul class="devise-bar">
    <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
      <li><%= link_to "Sign up", new_registration_path(resource_name) %></li>
    <% end -%>
  </ul>

  <ul class="devise-bar">
    <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
      <li><%= link_to "Forgot your password?", new_password_path(resource_name) %></li>
    <% end -%>
  </ul>
</div>